### ISSUE TITLE
different signatures in oauth.authorize

### ISSUE THREAD

**Issue by midnightcodr** [blinkmobile/hapi-oauth2orize#10]
Hello,
In the example oauth.authorize is passed with two different signatures, the first one is (request, reply, function ... ) and the second one is (function ...), was that an error? Because when token() is called, the following error is raised:
    TypeError: Uncaught error: Cannot read property 'lazy' of undefined 

at Object.internals.convertToExpress (/path/to/node_modules/hapi-oauth2orize/index.js:202:20)

```javascript
function authorize(request, reply) {
  oauth.authorize(request, reply, function (req, res) {
    reply.view('oauth', {transactionID: req.oauth2.transactionID});
  }, function (clientID, redirect, done) {
    server.helpers.find('client', clientID, function (docs) {
      done(null, docs[0], docs[0].redirect_uri);
    });
  });
};

function decision(request, reply) {
    oauth.decision(request, reply);
};

function token(request, reply) {
  oauth.authorize(function (clientID, redirect, done) {
    done(null, clientID, redirect);
  });
};
```

Also I wonder if it's possible to include authentication in the example. Should I use hapi-auth-cookie to handle authentication with auth2orize?

**Comment by midnightcodr** [comment]
I think I found the answer to my own question. The second oath.authorize should actually be oauth.token. I have forked this repo at https://github.com/midnightcodr/hapi-oauth2orize with a minor update to index.js and the example shown in README.md. This post https://hnryjms.github.io/2014/07/oauth2/ helped me a lot in figuring out the solution.

**Comment by devinivy** [comment]
Thanks!  The docs need a lot of work, and we'd definitely take the help.  Can you explain the change you made to index.js?

**Comment by lutfor3737** [comment]
Hey @midnightcodr  i am getting same error:

Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'lazy' of undefined
    at Object.internals.convertToExpress (/Users/Lutfor/Documents/test-api/node_modules/hapi-oauth2orize/index.js:201:20)
    at Object.internals.authorize (/Users/Lutfor/Documents/test-api/node_modules/hapi-oauth2orize/index.js:83:29)

what was your fix?

**Comment by lutfor3737** [comment]
@midnightcodr 
no issue(Uncaught error: Cannot read property 'lazy' of undefined
) after using your index.js file and example.  but i am getting another error when i am calling with curl command. I appreciate any kind of help from community to resolve this issue.

curl -XPOST "http://localhost:3000/oauth/token" -d "grant_type=password&client_id=abc123&client_secret=ssh-secret&username=bob&password=secret"

Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'find' of undefined
    at token (/Users/Lutfor/Documents/test-api/dist/index.js:196:17)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/Users/Lutfor/Documents/vincari-api/node_modules/hapi/lib/handler.js:96:36)
    at /Users/Lutfor/Documents/test-api/node_modules/hapi/lib/handler.js:30:23
    at internals.Protect.run.finish [as run] (/Users/Lutfor/Documents/test-api/node_modules/hapi/lib/protect.js:64:5)
    at exports.execute.finalize (/Users/Lutfor/Documents/test-api/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/Lutfor/Documents/test-api/node_modules/hapi/lib/request.js:383:16)
    at iterate (/Users/Lutfor/Documents/test-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/Lutfor/Documents/test-api/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth.test.internals.Auth.payload.finalize (/Users/Lutfor/Documents/test-api/node_modules/hapi/lib/auth.js:223:16)
    at each (/Users/Lutfor/Documents/test-api/node_modules/hapi/lib/request.js:383:16)
    at iterate (/Users/Lutfor/Documents/test-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/Lutfor/Documents/test-api/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at onParsed (/Users/Lutfor/Documents/test-api/node_modules/hapi/lib/route.js:409:20)
    at /Users/Lutfor/Documents/test-api/node_modules/hapi/lib/route.js:430:20
    at next (/Users/Lutfor/Documents/test-api/node_modules/hapi/node_modules/subtext/lib/index.js:43:16)
    at /Users/Lutfor/Documents/test-api/node_modules/hapi/node_modules/subtext/lib/index.js:164:20
